### PR TITLE
fix(darwin): remove debug symbols (`<lang>.so.dSYM`)

### LINKED ISSUE #28: macOS: remove debug symbols
On macOS, the parser directory has:

```
toml.so
toml.so.dSYM
```

If I delete it stays gone until I reinstall `tree-sitter-toml` then I have `toml.so.dSYM` again.

_Originally posted by @bottd in https://github.com/nvim-neorocks/rocks.nvim/issues/458#issuecomment-2209642193_

### PR DESCRIPTION
**Pull request by mrcjkb**
Fixes #28

### CODE REVIEW

**Comment by boltlessengineer** [comment]
Seems like when I install tree-sitter parsers from luarocks, I still get `.so.dSYM` files.
When/How will this PR affect to actual parsers on luarocks?

**Comment by mrcjkb** [comment]
That's strange. It should have been fixed long ago.
Which parser are you having issues with (name + version)?

**Comment by boltlessengineer** [comment]
basically every parsers I've installed from `rocks.nvim` (for example, `tree-sitter-go`).
I just remove all `~/.local/share/nvim`, `~/.local/state/nvim`, `~/.cache/nvim` and reinstalled all stuff with `rocks.nvim` and still having same issue.

I'm on macos 14.6.1 (aarch64-darwin) with nightly neovim (0.11)

```
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: dtd                  ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-dtd/parser/dtd.so
- ERROR Parser "dtd.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-dtd/parser/dtd.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'dtd.so' is not a valid language name
- OK Parser: json                 ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-json/parser/json.so
- ERROR Parser "json.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-json/parser/json.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'json.so' is not a valid language name
- OK Parser: dockerfile           ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-dockerfile/parser/dockerfile.so
- ERROR Parser "dockerfile.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-dockerfile/parser/dockerfile.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'dockerfile.so' is not a valid language name
- OK Parser: css                  ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-css/parser/css.so
- ERROR Parser "css.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-css/parser/css.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'css.so' is not a valid language name
- OK Parser: html                 ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-html/parser/html.so
- ERROR Parser "html.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-html/parser/html.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'html.so' is not a valid language name
- OK Parser: astro                ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-astro/parser/astro.so
- ERROR Parser "astro.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-astro/parser/astro.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'astro.so' is not a valid language name
- OK Parser: yaml                 ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-yaml/parser/yaml.so
- ERROR Parser "yaml.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-yaml/parser/yaml.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'yaml.so' is not a valid language name
- OK Parser: xml                  ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-xml/parser/xml.so
- ERROR Parser "xml.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-xml/parser/xml.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'xml.so' is not a valid language name
- OK Parser: vimdoc               ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-vimdoc/parser/vimdoc.so
- ERROR Parser "vimdoc.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-vimdoc/parser/vimdoc.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'vimdoc.so' is not a valid language name
- OK Parser: typescript           ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-typescript/parser/typescript.so
- ERROR Parser "typescript.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-typescript/parser/typescript.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'typescript.so' is not a valid language name
- OK Parser: tsx                  ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-tsx/parser/tsx.so
- ERROR Parser "tsx.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-tsx/parser/tsx.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'tsx.so' is not a valid language name
- OK Parser: toml                 ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-toml/parser/toml.so
- ERROR Parser "toml.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-toml/parser/toml.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'toml.so' is not a valid language name
- OK Parser: tmux                 ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-tmux/parser/tmux.so
- ERROR Parser "tmux.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-tmux/parser/tmux.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'tmux.so' is not a valid language name
- OK Parser: templ                ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-templ/parser/templ.so
- ERROR Parser "templ.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-templ/parser/templ.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'templ.so' is not a valid language name
- OK Parser: swift                ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-swift/parser/swift.so
- ERROR Parser "swift.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-swift/parser/swift.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'swift.so' is not a valid language name
- OK Parser: regex                ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-regex/parser/regex.so
- ERROR Parser "regex.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-regex/parser/regex.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'regex.so' is not a valid language name
- OK Parser: query                ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-query/parser/query.so
- ERROR Parser "query.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-query/parser/query.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'query.so' is not a valid language name
- OK Parser: nix                  ABI: 13, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-nix/parser/nix.so
- ERROR Parser "nix.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-nix/parser/nix.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'nix.so' is not a valid language name
- OK Parser: make                 ABI: 13, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-make/parser/make.so
- ERROR Parser "make.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-make/parser/make.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'make.so' is not a valid language name
- OK Parser: lua                  ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-lua/parser/lua.so
- ERROR Parser "lua.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-lua/parser/lua.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'lua.so' is not a valid language name
- OK Parser: kotlin               ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-kotlin/parser/kotlin.so
- ERROR Parser "kotlin.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-kotlin/parser/kotlin.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'kotlin.so' is not a valid language name
- OK Parser: jsonc                ABI: 13, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-jsonc/parser/jsonc.so
- ERROR Parser "jsonc.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-jsonc/parser/jsonc.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'jsonc.so' is not a valid language name
- OK Parser: javascript           ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-javascript/parser/javascript.so
- ERROR Parser "javascript.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-javascript/parser/javascript.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'javascript.so' is not a valid language name
- OK Parser: ini                  ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-ini/parser/ini.so
- ERROR Parser "ini.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-ini/parser/ini.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'ini.so' is not a valid language name
- OK Parser: groovy               ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-groovy/parser/groovy.so
- ERROR Parser "groovy.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-groovy/parser/groovy.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'groovy.so' is not a valid language name
- OK Parser: graphql              ABI: 13, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-graphql/parser/graphql.so
- ERROR Parser "graphql.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-graphql/parser/graphql.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'graphql.so' is not a valid language name
- OK Parser: gomod                ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-gomod/parser/gomod.so
- ERROR Parser "gomod.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-gomod/parser/gomod.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'gomod.so' is not a valid language name
- OK Parser: go                   ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-go/parser/go.so
- ERROR Parser "go.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-go/parser/go.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'go.so' is not a valid language name
- OK Parser: gitignore            ABI: 13, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-gitignore/parser/gitignore.so
- ERROR Parser "gitignore.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-gitignore/parser/gitignore.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'gitignore.so' is not a valid language name
- OK Parser: gitattributes        ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-gitattributes/parser/gitattributes.so
- ERROR Parser "gitattributes.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-gitattributes/parser/gitattributes.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'gitattributes.so' is not a valid language name
- OK Parser: editorconfig         ABI: 14, path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-editorconfig/parser/editorconfig.so
- ERROR Parser "editorconfig.so" failed to load (path: /Users/boltless/.local/share/nvim_rocks/site/pack/luarocks/opt/tree-sitter-editorconfig/parser/editorconfig.so.dSYM): ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:101: 'editorconfig.so' is not a valid language name
- OK Parser: bash                 ABI: 14, path: /usr/local/lib/nvim/parser/bash.so
- OK Parser: c                    ABI: 14, path: /usr/local/lib/nvim/parser/c.so
- OK Parser: help                 ABI: 14, path: /usr/local/lib/nvim/parser/help.so
- OK Parser: lua                  ABI: 14, path: /usr/local/lib/nvim/parser/lua.so
- OK Parser: markdown             ABI: 14, path: /usr/local/lib/nvim/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /usr/local/lib/nvim/parser/markdown_inline.so
- OK Parser: python               ABI: 14, path: /usr/local/lib/nvim/parser/python.so
- OK Parser: query                ABI: 14, path: /usr/local/lib/nvim/parser/query.so
- OK Parser: vim                  ABI: 14, path: /usr/local/lib/nvim/parser/vim.so
- OK Parser: vimdoc               ABI: 14, path: /usr/local/lib/nvim/parser/vimdoc.so
```

**Comment by boltlessengineer** [comment]
- checked with stable version of neovim and still same
- just realized ts parsers are now all versioned, try install `tree-sitter-rust v0.0.3` and still getting `.so.dSYM` file

should I make a new issue somewhere?

**Comment by mrcjkb** [comment]
I will look into it, no need to open another issue.

**Comment by mrcjkb** [comment]
I've pushed another fix, but will have to trigger a rebuild on the rocks-binaries servers, which will take some time.

**Comment by mrcjkb** [comment]
Should be fixed now.

**Comment by boltlessengineer** [comment]
Can confirm it is fixed. Thank you for your fast help!

**Pull request merged**
